# Generated by Django 4.1.5 on 2023-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_apiuser_delete_docuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
