# Generated by Django 4.1.5 on 2023-03-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_alter_apiuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
