# Generated by Django 4.1.7 on 2023-03-20 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_remove_apiuser_id_alter_apiuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
