# Generated by Django 4.1.7 on 2023-03-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_document_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_source_file',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_machine',
            field=models.TextField(null=True),
        ),
    ]
